name: base_flutter_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  r_dart_library: 0.4.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  localstorage: ^4.0.0+1
  path_provider: ^2.0.2
  flutter_file_path_provider: ^0.0.3
  package_info: ^2.0.2
  provider: ^5.0.0
  url_launcher: ^6.0.6
  event_bus: ^2.0.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.0+3
  cached_network_image: ^3.0.0
  sqflite: ^2.0.0+3
  device_info: ^2.0.2
  oktoast: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - packages/base_flutter_app/assets/images/test1.png
flutter_intl:
  enabled: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images/
  - lib/assets/jsons/
  fonts: []
